on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: "1.15.7" # The Go version to download (if necessary) and use.
      - run: go get ./...
      - run: go build bitscreen.go
